// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function optionMap(x) {
  if (x !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(x));
  }
  
}

function AnyName$A(props) {
  return React.createElement("div", {
              id: props.id,
              name: props.name
            }, "component A");
}

var A = {
  make: AnyName$A
};

function AnyName$WithoutParens(props) {
  return React.createElement(AnyName$A, {
              name: optionMap(props.name)
            });
}

var WithoutParens = {
  make: AnyName$WithoutParens
};

export {
  optionMap ,
  A ,
  WithoutParens ,
}
/* react Not a pure module */
