// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function optionMap(x) {
  if (x !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(x));
  }
  
}

function AnyName$A(props) {
  return JsxRuntime.jsx("div", {
              children: "component A",
              id: props.id,
              name: props.name
            });
}

var A = {
  make: AnyName$A
};

function AnyName$WithoutParens(props) {
  return JsxRuntime.jsx(AnyName$A, {
              name: optionMap(props.name)
            });
}

var WithoutParens = {
  make: AnyName$WithoutParens
};

export {
  optionMap ,
  A ,
  WithoutParens ,
}
/* react/jsx-runtime Not a pure module */
