// Generated by ReScript, PLEASE EDIT WITH CARE

import * as V4 from "./V4.bs.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.bs.js";

function App(props) {
  return React.createElement(RescriptReactErrorBoundary.make, {
              children: React.createElement(React.Suspense, {
                    children: Caml_option.some(React.createElement("div", undefined, React.createElement(V4.make, {}), "div!")),
                    fallback: Caml_option.some(React.createElement("div", undefined, "loading.."))
                  }),
              fallback: (function (param) {
                  return React.createElement("div", undefined, "error!");
                })
            });
}

var make = App;

export {
  make ,
}
/* V4 Not a pure module */
