// Generated by ReScript, PLEASE EDIT WITH CARE


function AliasProps$C1(props) {
  var text = props.text;
  var text$1 = text !== undefined ? text : "Test";
  return props.priority + text$1;
}

var C1 = {
  make: AliasProps$C1
};

var x = {
  a: 1,
  b: 3
};

export {
  x ,
  C1 ,
}
/* No side effect */
