// Generated by ReScript, PLEASE EDIT WITH CARE


var a = "foo";

function DefaultValueProp$C2(props) {
  var a__ = props.a;
  if (a__ !== undefined) {
    return a__;
  } else {
    return a;
  }
}

var C2 = {
  a: a,
  make: DefaultValueProp$C2
};

function DefaultValueProp$C3(props) {
  var everythingDisabled__ = props.disabled;
  var everythingDisabled = everythingDisabled__ !== undefined ? everythingDisabled__ : false;
  if (everythingDisabled) {
    return "true";
  } else {
    return "false";
  }
}

var C3 = {
  make: DefaultValueProp$C3
};

export {
  C2 ,
  C3 ,
}
/* No side effect */
