// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var make = React.forwardRef(function (props, ref) {
      var tmp = {
        type: "text"
      };
      var tmp$1 = Belt_Option.map((ref == null) ? undefined : Caml_option.some(ref), (function (prim) {
              return prim;
            }));
      if (tmp$1 !== undefined) {
        tmp.ref = Caml_option.valFromOption(tmp$1);
      }
      if (props.className !== undefined) {
        tmp.className = Caml_option.valFromOption(props.className);
      }
      return React.createElement("div", undefined, React.createElement("input", tmp), props.children);
    });

var FancyInput = {
  make: make
};

function DiscouragedForwardRef(props) {
  var input = React.useRef(null);
  var onClick = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(input.current), (function (input) {
            input.focus();
          }));
  };
  return React.createElement("div", undefined, React.createElement(make, {
                  ref: input,
                  className: "fancy",
                  children: React.createElement("button", {
                        onClick: onClick
                      }, "Click to focus")
                }));
}

var make$1 = DiscouragedForwardRef;

export {
  FancyInput ,
  make$1 as make,
}
/* make Not a pure module */
