// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

var make = React.forwardRef(function (props, ref) {
      return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("input", {
                          ref: Belt_Option.map((ref == null) ? undefined : Caml_option.some(ref), (function (prim) {
                                  return prim;
                                })),
                          className: props.className,
                          type: "text"
                        }),
                    props.children
                  ]
                });
    });

var FancyInput = {
  make: make
};

function DiscouragedForwardRef(props) {
  var input = React.useRef(null);
  var onClick = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(input.current), (function (input) {
            input.focus();
          }));
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(make, {
                    className: "fancy",
                    children: JsxRuntime.jsx("button", {
                          children: "Click to focus",
                          onClick: onClick
                        }),
                    ref: input
                  })
            });
}

var make$1 = DiscouragedForwardRef;

export {
  FancyInput ,
  make$1 as make,
}
/* make Not a pure module */
