// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function FirstClassModule$Select(Props) {
  return React.createElement("div", undefined);
}

var Select = {
  make: FirstClassModule$Select
};

export {
  Select ,
}
/* react Not a pure module */
