// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var make = React.forwardRef(function (props, ref) {
      return React.createElement("div", undefined, React.createElement("input", {
                      ref: Belt_Option.map((ref == null) ? undefined : Caml_option.some(ref), (function (prim) {
                              return prim;
                            })),
                      className: props.className,
                      type: "text"
                    }), props.children);
    });

var FancyInput = {
  make: make
};

function ForwardRef$V4C(props) {
  var input = React.useRef(null);
  var onClick = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(input.current), (function (input) {
            input.focus();
          }));
  };
  return React.createElement("div", undefined, React.createElement(make, {
                  children: React.createElement("button", {
                        onClick: onClick
                      }, "Click to focus"),
                  ref: input
                }));
}

var V4C = {
  FancyInput: FancyInput,
  make: ForwardRef$V4C
};

function ForwardRef(props) {
  return React.createElement(ForwardRef$V4C, {});
}

var make$1 = ForwardRef;

export {
  V4C ,
  make$1 as make,
}
/* make Not a pure module */
