// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Greeting$CustomTextInput(props) {
  return React.createElement("div", undefined, React.createElement("input", {
                  ref: Caml_option.some(props.setInputRef),
                  type: "text"
                }));
}

var CustomTextInput = {
  make: Greeting$CustomTextInput
};

function Greeting(props) {
  var textInput = React.useRef(null);
  var setInputRef = function (element) {
    textInput.current = element;
  };
  return React.createElement(Greeting$CustomTextInput, {
              setInputRef: setInputRef
            });
}

var make = Greeting;

export {
  CustomTextInput ,
  make ,
}
/* react Not a pure module */
