// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Interface$A(props) {
  return props.x;
}

var A = {
  make: Interface$A
};

function Interface$NoProps(props) {
  return JsxRuntime.jsx("div", {});
}

var NoProps = {
  make: Interface$NoProps
};

export {
  A ,
  NoProps ,
}
/* react/jsx-runtime Not a pure module */
