// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Interface$A(props) {
  return props.x;
}

var A = {
  make: Interface$A
};

function Interface$NoProps(props) {
  return React.createElement("div", undefined);
}

var NoProps = {
  make: Interface$NoProps
};

export {
  A ,
  NoProps ,
}
/* react Not a pure module */
