// Generated by ReScript, PLEASE EDIT WITH CARE


function LazyComp$default(props) {
  return props.x;
}

var $$default = LazyComp$default;

export {
  $$default ,
  $$default as default,
}
/* No side effect */
