// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function MangleKeyword$C30(Props) {
  return Props.open;
}

var C30 = {
  make: MangleKeyword$C30
};

var C31 = {};

var c30 = React.createElement(MangleKeyword$C30, {
      open: "x"
    });

var c31 = React.createElement(default, {
      open: "x"
    });

function MangleKeyword$C4C0(props) {
  return props.open;
}

var C4C0 = {
  make: MangleKeyword$C4C0
};

var C4C1 = {};

var c4c0 = React.createElement(MangleKeyword$C4C0, {
      open: "x",
      type: "t"
    });

var c4c1 = React.createElement(default, {
      open: "x",
      type: "t"
    });

function MangleKeyword$C4A0(props) {
  return props.open;
}

var C4A0 = {
  make: MangleKeyword$C4A0
};

var C4A1 = {};

var c4a0 = JsxRuntime.jsx(MangleKeyword$C4A0, {
      open: "x",
      type: "t"
    });

var c4a1 = JsxRuntime.jsx(default, {
      open: "x",
      type: "t"
    });

export {
  C30 ,
  C31 ,
  c30 ,
  c31 ,
  C4C0 ,
  C4C1 ,
  c4c0 ,
  c4c1 ,
  C4A0 ,
  C4A1 ,
  c4a0 ,
  c4a1 ,
}
/* c30 Not a pure module */
