// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function Memo$TestMemoCustomComparePropsNew(props) {
  return props.foo;
}

var make = React.memo(Memo$TestMemoCustomComparePropsNew, (function (nextProps, currentProps) {
        return nextProps.foo === currentProps.foo;
      }));

var TestMemoCustomComparePropsNew = {
  make: make
};

function memo(__x) {
  return React.memo(__x, (function (nextProps, currentProps) {
                return Caml_obj.equal(nextProps.foo, currentProps.foo);
              }));
}

var make$1 = memo(function (props) {
      return props.foo;
    });

var TestMemoCustomComparePropsOld = {
  memo: memo,
  make: make$1
};

export {
  TestMemoCustomComparePropsNew ,
  TestMemoCustomComparePropsOld ,
}
/* make Not a pure module */
