// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@rescript/react/src/React.bs.js";
import * as React$1 from "react";

function NoPropsWithKey$V4CA(props) {
  return React$1.createElement("div", {
              key: "nopropswithkey-div",
              "aria-busy": true,
              id: "!!!"
            }, "!!!");
}

var V4CA = {
  make: NoPropsWithKey$V4CA
};

function NoPropsWithKey$V4C(props) {
  return React$1.createElement(React$1.Fragment, undefined, React.createElementWithKey(NoPropsWithKey$V4CA, {}, "k"));
}

var V4C = {
  make: NoPropsWithKey$V4C
};

export {
  V4CA ,
  V4C ,
}
/* React Not a pure module */
