// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

function NoPropsWithKey$V4CA(props) {
  return React.createElement("div", {
              key: "nopropswithkey-div",
              "aria-busy": true,
              id: "!!!"
            }, "!!!");
}

var V4CA = {
  make: NoPropsWithKey$V4CA
};

function NoPropsWithKey$V4C(props) {
  return React.createElement(React.Fragment, undefined, JsxPPXReactSupport.createElementWithKey("k", NoPropsWithKey$V4CA, {}));
}

var V4C = {
  make: NoPropsWithKey$V4C
};

export {
  V4CA ,
  V4C ,
}
/* react Not a pure module */
