// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function format(user) {
  return "Dr." + user.lastName;
}

function OptimizeAutomaticMode$User(props) {
  return JsxRuntime.jsx("h1", {
              children: Caml_option.some("Dr." + props.doctor.lastName),
              id: "h1"
            });
}

var User = {
  format: format,
  make: OptimizeAutomaticMode$User
};

export {
  User ,
}
/* react/jsx-runtime Not a pure module */
