// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SomeLib from "some-lib";

function SomeLib$1(T) {
  var $$Screen = {};
  return {
          $$Screen: $$Screen
        };
}

function ReactNavigation$SomeComponent(props) {
  return "Some component";
}

var SomeComponent = {
  make: ReactNavigation$SomeComponent
};

var $$Screen = {};

var SomeComp = {
  $$Screen: $$Screen
};

function render(param) {
  return React.createElement(SomeLib.Screen, {
              component: ReactNavigation$SomeComponent
            });
}

export {
  SomeLib$1 as SomeLib,
  SomeComponent ,
  SomeComp ,
  render ,
}
/* react Not a pure module */
