// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

function RemovedKeyProp$Foo(props) {
  return props.x + props.y;
}

var Foo = {
  make: RemovedKeyProp$Foo
};

function RemovedKeyProp$HasChildren(props) {
  return React.createElement(React.Fragment, undefined, props.children);
}

var HasChildren = {
  make: RemovedKeyProp$HasChildren
};

function RemovedKeyProp(props) {
  return React.createElement(React.Fragment, undefined, JsxPPXReactSupport.createElementWithKey("k1", RemovedKeyProp$Foo, {
                  x: "x",
                  y: "y"
                }), React.createElement(RemovedKeyProp$Foo, {
                  x: "x",
                  y: "y"
                }), JsxPPXReactSupport.createElementWithKey("k2", RemovedKeyProp$HasChildren, {
                  children: React.createElement(RemovedKeyProp$Foo, {
                        x: "x",
                        y: "y"
                      })
                }), React.createElement(RemovedKeyProp$HasChildren, {
                  children: React.createElement(RemovedKeyProp$Foo, {
                        x: "x",
                        y: "y"
                      })
                }));
}

var make = RemovedKeyProp;

export {
  Foo ,
  HasChildren ,
  make ,
}
/* react Not a pure module */
