// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@rescript/react/src/React.bs.js";
import * as React$1 from "react";

function RemovedKeyProp$Foo(props) {
  return props.x + props.y;
}

var Foo = {
  make: RemovedKeyProp$Foo
};

function RemovedKeyProp$HasChildren(props) {
  return React$1.createElement(React$1.Fragment, undefined, props.children);
}

var HasChildren = {
  make: RemovedKeyProp$HasChildren
};

function RemovedKeyProp(props) {
  return React$1.createElement(React$1.Fragment, undefined, React.createElementWithKey(RemovedKeyProp$Foo, {
                  x: "x",
                  y: "y"
                }, "k1"), React$1.createElement(RemovedKeyProp$Foo, {
                  x: "x",
                  y: "y"
                }), React.createElementWithKey(RemovedKeyProp$HasChildren, {
                  children: React$1.createElement(RemovedKeyProp$Foo, {
                        x: "x",
                        y: "y"
                      })
                }, "k2"), React$1.createElement(RemovedKeyProp$HasChildren, {
                  children: React$1.createElement(RemovedKeyProp$Foo, {
                        x: "x",
                        y: "y"
                      })
                }));
}

var make = RemovedKeyProp;

export {
  Foo ,
  HasChildren ,
  make ,
}
/* React Not a pure module */
