// Generated by ReScript, PLEASE EDIT WITH CARE


function SharedProps$V4C1(props) {
  return props.x + props.y;
}

var V4C1 = {
  make: SharedProps$V4C1
};

function SharedProps$V4C2(props) {
  return props.x + props.y;
}

var V4C2 = {
  make: SharedProps$V4C2
};

var V4C3 = {};

function SharedProps$V4A1(props) {
  return props.x + props.y;
}

var V4A1 = {
  make: SharedProps$V4A1
};

function SharedProps$V4A2(props) {
  return props.x + props.y;
}

var V4A2 = {
  make: SharedProps$V4A2
};

var V4A3 = {};

export {
  V4C1 ,
  V4C2 ,
  V4C3 ,
  V4A1 ,
  V4A2 ,
  V4A3 ,
}
/* No side effect */
