// Generated by ReScript, PLEASE EDIT WITH CARE


function SpreadProps$A(props) {
  return props.x + props.y;
}

var A = {
  make: SpreadProps$A
};

var p = {
  x: "x+",
  y: "y+"
};

var p0 = {
  x: "x0",
  y: "y0"
};

var p1 = {
  x: "x1",
  y: "y1"
};

export {
  A ,
  p ,
  p0 ,
  p1 ,
}
/* No side effect */
