// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SpreadProps$A(props) {
  return props.x + props.y;
}

var A = {
  make: SpreadProps$A
};

var _c2 = React.createElement(SpreadProps$A, {
      x: "x",
      y: "y+"
    });

var p = {
  x: "x+",
  y: "y+"
};

var p0 = {
  x: "x0",
  y: "y0"
};

var p1 = {
  x: "x1",
  y: "y1"
};

export {
  A ,
  p ,
  p0 ,
  p1 ,
  _c2 ,
}
/* _c2 Not a pure module */
