// Generated by ReScript, PLEASE EDIT WITH CARE


function Uncurried(props) {
  return props.a + props.b;
}

var make = Uncurried;

var a = {
  a: "a"
};

var b = {
  b: "b"
};

export {
  make ,
  a ,
  b ,
}
/* No side effect */
