// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function V4$Foo(props) {
  return React.createElement("div", undefined, props.name);
}

var Foo = {
  make: V4$Foo
};

function V4$Bar(props) {
  return React.createElement("div", undefined, Belt_Option.getWithDefault(props.name, ""), props.children);
}

var Bar = {
  make: V4$Bar
};

function V4$Baz(props) {
  var name = props.name;
  var name$1 = name !== undefined ? name : "baz";
  return React.createElement("div", {
              id: props.id2
            }, name$1, props.children);
}

var Baz = {
  make: V4$Baz
};

var x = 1;

var a = {
  x: x
};

var b = {
  x: Belt_Option.map(x, (function (x) {
          return x;
        }))
};

function V4(props) {
  return Belt_Option.getWithDefault(props.b, "V4..");
}

var make = V4;

export {
  Foo ,
  Bar ,
  Baz ,
  x ,
  a ,
  b ,
  make ,
}
/* b Not a pure module */
